# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Scopri Roma
email: sasadangelo@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Roa Tour guida i visitatori alla scoperta di Roma, dai monumenti iconici
  ai tesori nascosti. Trova itinerari unici e consigli per esplorare la
  storia, l'arte e la cultura della Città Eterna.e description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.scopriroma.it" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

logo: /assets/img/scopri-roma-logo.webp
permalink: /:title/

# Build settings
theme: minimal-mistakes-jekyll
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

assets:
  stylesheets:
    - /assets/css/main.scss
    - /_sass/custom.scss

locale                   : "it-IT"
classes: wide

pagination:
  enabled: true
  per_page: 7
  permalink: '/blog/:num/' # URL per le pagine successive

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-QJ6879Y4WN"
    anonymize_ip: false # default
google_site_verification: "z-T9lWqcZAdtpMew4wZhrunV1RQsjuRmax3mn5zb2BI"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
